In [88]:
#isso deve vir antes de todo o código
import numpy as np 
import time

ti = time.time()

# Definindo uma matriz 
A = np.array([  [1,1,1,1]  , [2,1,-1,1] , [2,-1,1,1] , [2,-1,1,6] ])

# Armazenamos o n. de linhas (m) e colunas (n)
m, n = A.shape

#Criando matriz identidade com mesma dimensao da A
C = np.eye(m,n)

#Exibindo a matriz A
#print('A=\n',A)

#Vamos iniciar a implementação da eliminação de Gauss
for k in range(0,n-1): # [0,1,2]

    #Exibindo k
    #print('k=',k)
    
    #Aqui mostramos o pivo atual
    #print('O elemento pivô atual é:',A[k,k])

    for i in range(k+1,m):

        #print(A[i,k],' é um elemento abaixo do pivô')
        
        #Vamos calcular os multiplicadores
        C[i,k] = A[i,k] / A[k,k]

        for j in range(k,n):

            A[i,j] = A[i,j] - C[i,k] * A[k,j]


tf = time.time()


tempo_execucao = tf - ti

print(f'Tempo de execução: {tempo_execucao} segundos')

print('C=\n',C)
print('A=\n',A)

Tempo de execução: 0.0012090206146240234 segundos
C=
 [[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [2. 3. 1. 0.]
 [2. 3. 1. 1.]]
A=
 [[ 1  1  1  1]
 [ 0 -1 -3 -1]
 [ 0  0  8  2]
 [ 0  0  0  5]]


é v
